# Generated by Django 6.0.2 on 2026-03-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0003_alter_commentreplylike_unique_together_extrasocial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasocial',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
