# Generated by Django 6.0.2 on 2026-03-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0004_extrasocial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasocial',
            name='url',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='usersocials',
            name='github',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersocials',
            name='linkedin',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersocials',
            name='website',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usersocials',
            name='youtube',
            field=models.CharField(blank=True, default=''),
        ),
    ]
