# Generated by Django 6.0.2 on 2026-03-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('login_email', 'login email'), ('log_ip', 'login IP')], max_length=50)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_time', models.PositiveIntegerField(default=900, help_text='lockout time in seconds')),
            ],
            options={
                'unique_together': {('scope', 'role')},
            },
        ),
    ]
