# Generated by Django 6.0.2 on 2026-03-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_throttlesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThrottleSettings',
        ),
    ]
