# Generated by Django 6.0.2 on 2026-03-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_throttlesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_time', models.PositiveIntegerField(default=900, help_text='lockout time in seconds')),
            ],
        ),
    ]
