# Generated by Django 6.0.2 on 2026-03-04 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_throttlesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('locked', 'Account Locked')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-blacklisted_at'],
            },
        ),
        migrations.DeleteModel(
            name='ThrottleSettings',
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenblacklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
        migrations.AddIndex(
            model_name='loginaudit',
            index=models.Index(fields=['email_attempted', 'attempted_at'], name='users_login_email_a_f47217_idx'),
        ),
        migrations.AddIndex(
            model_name='loginaudit',
            index=models.Index(fields=['ip_address', 'attempted_at'], name='users_login_ip_addr_81f0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['token'], name='users_token_token_81995b_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['user'], name='users_token_user_id_e2720d_idx'),
        ),
    ]
