# Generated by Django 6.0.2 on 2026-03-07 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_email_otp_user_email_otp_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 7, 13, 58, 6, 889800, tzinfo=datetime.timezone.utc)),
        ),
    ]
