# Generated by Django 6.0.2 on 2026-03-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_customuser_is_staff_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
