# Generated by Django 6.0.2 on 2026-03-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_customuser_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_of_logins',
            field=models.IntegerField(default=True),
        ),
    ]
