# Generated by Django 6.0.2 on 2026-03-08 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0004_customuser_number_of_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_failed_attempts',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number_of_logins',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
