# Generated by Django 6.0.2 on 2026-03-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_customuser_last_failed_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_failed_attempts',
        ),
    ]
