# Generated by Django 6.0.2 on 2026-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0006_remove_customuser_last_failed_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
