# Generated by Django 6.0.2 on 2026-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0007_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_otp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
