# Generated by Django 6.0.2 on 2026-03-24 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0010_customuser_bio_customuser_github_customuser_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasocials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_socials', to=settings.AUTH_USER_MODEL),
        ),
    ]
