# Generated by Django 6.0.2 on 2026-03-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0011_alter_extrasocials_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='youtube',
        ),
        migrations.DeleteModel(
            name='ExtraSocials',
        ),
    ]
