# Generated by Django 6.0.2 on 2026-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('car wash', ' Car Wash'), ('garage service', 'Garage Service')])),
                ('wash_level', models.CharField(choices=[('basic wash', 'Basic Wash'), ('premium wash', 'Premium Wash')])),
                ('wash_type', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('interior & exterior', 'Interior & Exterior')])),
                ('car_type', models.CharField(choices=[('truck', 'Truck'), ('vehicle', 'Vehicle'), ('motorcycle', 'Motorcycle')])),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField()),
                ('pickup', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
