# Generated by Django 6.0.2 on 2026-03-05 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cta_text', models.CharField(default='Learn More', max_length=100)),
                ('url', models.URLField()),
                ('topic', models.CharField(choices=[('serializers', 'Serializers'), ('views', 'Views & ViewSets'), ('authentication', 'Authentication & JWT'), ('permissions', 'Permissions & Throttling'), ('pagination', 'Pagination'), ('filtering', 'Filtering & Searching'), ('validation', 'Validation'), ('advanced', 'Advanced Topics'), ('best_practices', 'Best Practices'), ('troubleshooting', 'Troubleshooting')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'is_active'], name='smartpython_topic_1ec289_idx'), models.Index(fields=['difficulty', 'is_active'], name='smartpython_difficu_d614cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_question', models.BooleanField(default=False)),
                ('is_answer', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='smartpythonists.comment')),
            ],
            options={
                'ordering': ['-likes_count', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('topic', models.CharField(choices=[('serializers', 'Serializers'), ('views', 'Views & ViewSets'), ('authentication', 'Authentication & JWT'), ('permissions', 'Permissions & Throttling'), ('pagination', 'Pagination'), ('filtering', 'Filtering & Searching'), ('validation', 'Validation'), ('advanced', 'Advanced Topics'), ('best_practices', 'Best Practices'), ('troubleshooting', 'Troubleshooting')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('reply_to_comment', 'Someone replied to your comment'), ('answer_to_question', 'Someone answered your question'), ('mention', 'You were mentioned'), ('new_post', 'New post in your favorite topic'), ('post_update', 'A post you commented on was updated')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartpythonists.comment')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartpythonists.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='smartpythonists.post'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('serializers', 'Serializers'), ('views', 'Views & ViewSets'), ('authentication', 'Authentication & JWT'), ('permissions', 'Permissions & Throttling'), ('pagination', 'Pagination'), ('filtering', 'Filtering & Searching'), ('validation', 'Validation'), ('advanced', 'Advanced Topics'), ('best_practices', 'Best Practices'), ('troubleshooting', 'Troubleshooting')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('documentation', 'Official Documentation'), ('youtube', 'YouTube Tutorial'), ('course', 'Online Course'), ('book', 'Book'), ('article', 'Article/Blog'), ('github', 'GitHub Repository'), ('tool', 'Tool/Library')], max_length=50)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=200)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('rating', models.FloatField(blank=True, help_text='1-5 stars', null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-reviews_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('learned_topics', models.JSONField(default=list)),
                ('posts_read', models.IntegerField(default=0)),
                ('comments_made', models.IntegerField(default=0)),
                ('questions_asked', models.IntegerField(default=0)),
                ('answers_given', models.IntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Progress',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='smartpythonists.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'user'], name='smartpython_comment_6df939_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic', '-published_at'], name='smartpython_topic_4d180f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['difficulty', '-published_at'], name='smartpython_difficu_e53a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-published_at'], name='smartpython_is_publ_1a62c5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='smartpython_user_id_e69eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='smartpython_user_id_1e15e6_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='smartpython_post_id_235b69_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='smartpython_author__cf819f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment', 'created_at'], name='smartpython_parent__71ab06_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['topic', 'difficulty'], name='smartpython_topic_52da3d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['topic', '-rating'], name='smartpython_topic_2e6c09_idx'),
        ),
    ]
